// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2LzUgB1y0_GXsyoO8APPSGu1rZ3qSPtI',
    appId: '1:400788659874:web:c86866536ffe89c636c1fb',
    messagingSenderId: '400788659874',
    projectId: 'apmt-620e9',
    authDomain: 'apmt-620e9.firebaseapp.com',
    storageBucket: 'apmt-620e9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9s9OLtHA_cSeoQXA0G5seP0MItqYT4kM',
    appId: '1:400788659874:android:6123f515372cfcce36c1fb',
    messagingSenderId: '400788659874',
    projectId: 'apmt-620e9',
    storageBucket: 'apmt-620e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUJyadJcYyzGY1B3z5EjHHTLCva6Dzz94',
    appId: '1:400788659874:ios:b3fb59960aebc56736c1fb',
    messagingSenderId: '400788659874',
    projectId: 'apmt-620e9',
    storageBucket: 'apmt-620e9.firebasestorage.app',
    iosBundleId: 'com.example.apmt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUJyadJcYyzGY1B3z5EjHHTLCva6Dzz94',
    appId: '1:400788659874:ios:b3fb59960aebc56736c1fb',
    messagingSenderId: '400788659874',
    projectId: 'apmt-620e9',
    storageBucket: 'apmt-620e9.firebasestorage.app',
    iosBundleId: 'com.example.apmt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2LzUgB1y0_GXsyoO8APPSGu1rZ3qSPtI',
    appId: '1:400788659874:web:960c301dcc3ae29836c1fb',
    messagingSenderId: '400788659874',
    projectId: 'apmt-620e9',
    authDomain: 'apmt-620e9.firebaseapp.com',
    storageBucket: 'apmt-620e9.firebasestorage.app',
  );
}
